aws:
  project_region: 'eu-west-2'
  appsync:
    region: 'eu-west-2'
    authenticationType: 'AWS_IAM'
  ssl_cert: arn:aws:acm:us-east-1:305156261037:certificate/e3969a88-3cf1-42a8-8a54-c2af934533c3
  dns_prefix: prod
  account_id: 305156261037

tenants:
  672FB50-BE2B-405D-9526-CB81427B7B7E:
    enabled: false
    userPoolId: eu-west-2_8RE7DybZy
    userPoolWebClientId: 7sdciv6jagbpqgpsgnbf0tdc4f
    assetImagesS3Bucket: reams-elias-mwa-prod-tenant1-images

  BA7E007F-761B-4A0F-AFAF-45B032AC19A2: #englandrugby.com
    enabled: false
    userPoolId: eu-west-2_xINWb4hzT
    userPoolWebClientId: 4n1u37k6kpfejs2aj51vpcbc5p
    assetImagesS3Bucket: reams-elias-mwa-prod-tenant2-images

  8720A63-FCE4-328E-3321-AD3F58797C7F:
    enabled: false
    userPoolId: eu-west-2_s05xLtPVX
    userPoolWebClientId: 5shd7g7t0svj5fgai29fphula9
    assetImagesS3Bucket: reams-elias-mwa-prod-tenant3-images

  3333333-3333-3333-3333-333333333333: #test tenant
    userPoolId: eu-west-2_U13PMDKe4
    userPoolWebClientId: s5319kbpli9eum7118aee2ev9
    assetImagesS3Bucket: reams-elias-mwa-prod-test-tenant-images

  1111111-1111-1111-1111-111111111111:
    enabled: false
    userPoolId: eu-west-2_rvy72NPiq
    userPoolWebClientId: 45mvjvub8mlh40ce0rp57ec72i
    assetImagesS3Bucket: reams-elias-mwa-prod-reams-images

  90C8BE2E-AB81-45B5-A9DB-A6F967471C1D: #atkins
    enabled: true
    userPoolId: eu-west-2_fyfd1IV6r
    userPoolWebClientId: 69cr52h2bpj60g235qigae6jff
    assetImagesS3Bucket: reams-elias-mwa-prod-atkins-images
    cleanUp:
      lambdaDisabled: true
      localDisabled: false

  91139949-B379-4EC7-AD72-45BEB7DBB9B8: #20fcst
    enabled: false
    userPoolId: eu-west-2_LlIEn2bAs
    userPoolWebClientId: 6aqqjtuo20od60vm8js9pphvm9
    assetImagesS3Bucket: reams-elias-mw-prod-20fcst-images
    cleanUp:
      lambdaDisabled: true
      localDisabled: false

  9692179F-A1B5-4045-AA6C-0A3FD1D49DE8: #allianz
    enabled: true
    userPoolId: eu-west-2_7y2A8jUr7
    userPoolWebClientId: 32h6t1tlsov2qmra0d3nqt2gg8
    assetImagesS3Bucket: reams-elias-mwa-prod-allianz-images
    cleanUp:
      lambdaDisabled: true
      localDisabled: false

  93FC987A-9705-495A-BA65-37654374EB4C: #rhc
    enabled: false
    userPoolId: eu-west-2_jCmnxEnM7
    userPoolWebClientId: 4dfi572eqa3aj85iag6t59khmk
    assetImagesS3Bucket: reams-elias-mwa-prod-rhc-images
    cleanUp:
      lambdaDisabled: true
      localDisabled: false

  97000000-0000-0000-0000-00000000001: #airbus
    enabled: true
    userPoolId: eu-west-2_GMasoEWl5
    userPoolWebClientId: 7gr7oegjsgoo8meoqca8adcuc2
    assetImagesS3Bucket: reams-elias-mwa-prod-airbus-images
    cleanUp:
      lambdaDisabled: true

  admin:
    assetImagesS3Bucket: reams-elias-mwa-prod-admin-images

globalUser:
  userPoolId: eu-west-2_gd8iQVRsL
  userPoolWebClientId: 583879m026djtii4m3b78qsvqs


adalConfig:
  tenant: d87c0cf5-fd89-4d04-92c0-eb35aeea365d
  clientId: c3a6bb81-b75e-4442-a219-6b5e28403325


elasticSearchEndpoint: https://search-reams-elias-mwa-prod-es-ylejoxai7nvoiazcwtlib74y5m.eu-west-2.es.amazonaws.com
elasticSearchArn: arn:aws:es:eu-west-2:305156261037:domain/reams-elias-mwa-prod-es

logSubscriptionEnabled: true

cleanUp:
  lambdaDisabled: true

googleApiKey: AIzaSyAOZ4aGqQInHWOhA04CFCxwRrVYEhYyGds
