export const item = {
  quantity: '1',
  condition: 'B',
  'install-date': '2019-08-05T07:36:50.899Z',
  barcode: '318072191',
  'existing-asset-number': 'bite',
  accessibility: 'High Level (>3m)',
  'asset-status': 'Decommissioned',
  criticality: 'Medium',
  manufacturer: 'LEROY - SOMER',
  model: 'numeral',
  'maintenance-requirement': 'Maintain',
  'notes.description': 'local description',
  'notes.notes': 'notes',
  'notes.condition': 'conditional description',
  rating: '5',
}
export const assetDetail = {
  facets: [
    {
      element: 'notes',
      key: 'description',
      value: 'Local Asset Description',
      type: 'TextBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 1,
      group: 'Description',
    },
    {
      element: 'facets',
      key: 'quantity',
      value: 'Quantity',
      type: 'TextBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 5,
      group: 'Description',
    },
    {
      element: 'facets',
      key: 'condition',
      value: 'Condition',
      type: 'ComboBox',
      order: 80,
      group: 'Description',
      validation: {
        allowByPass: false,
        mandatory: true,
        isRegEx: false,
        value: '2235, 2236, 2237, 2238',
      },
      options: [
        { code: 'A', description: 'A', legacyId: 1 },
        { code: 'B', description: 'B', legacyId: 2 },
        { code: 'C', description: 'C', legacyId: 3 },
        { code: 'CX', description: 'CX', legacyId: 4 },
        { code: 'D', description: 'D', legacyId: 5 },
        { code: 'DX', description: 'DX', legacyId: 6 },
      ],
    },
    {
      element: 'facets',
      key: 'install-date',
      value: 'Install Date',
      type: 'ComboBoxYear',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 10,
      group: 'Others',
    },
    {
      element: 'facets',
      key: 'barcode',
      value: 'Barcode',
      type: 'BarcodeBox',
      order: 15,
      group: 'Others',
      copyable: false,
      validation: {
        allowByPass: false,
        mandatory: true,
        isRegEx: true,
        value: '^[0-9]{9}$#Must contain 9 numbers',
      },
    },
    {
      element: 'facets',
      key: 'existing-asset-number',
      value: 'Existing Asset Number',
      type: 'TextBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 20,
      group: 'Others',
      copyable: false,
    },
    {
      element: 'facets',
      key: 'accessibility',
      value: 'Accessibility',
      type: 'ComboBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 40,
      group: 'Others',
      options: [
        { code: 'Low Level (<3m)', description: 'Low Level (<3m)', legacyId: 1 },
        { code: 'High Level (>3m)', description: 'High Level (>3m)', legacyId: 2 },
      ],
    },
    {
      element: 'notes',
      key: 'condition',
      value: 'Condition Description (Must be a sentence)',
      type: 'MultiLineTextBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 85,
      group: 'Others',
    },
    {
      element: 'facets',
      key: 'asset-status',
      value: 'Asset Status',
      type: 'ComboBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 95,
      group: 'Others',
      options: [
        { code: 'Operating', description: 'Operating', legacyId: 1 },
        { code: 'Decommissioned', description: 'Decommissioned', legacyId: 2 },
        { code: 'Not Ready', description: 'Not Ready', legacyId: 3 },
      ],
    },
    {
      element: 'facets',
      key: 'criticality',
      value: 'Criticality',
      type: 'ComboBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 100,
      group: 'Others',
      options: [
        { code: 'Urgent', description: 'Urgent', legacyId: 1 },
        { code: 'High', description: 'High', legacyId: 2 },
        { code: 'Medium', description: 'Medium', legacyId: 3 },
      ],
    },
    {
      element: 'notes',
      key: 'notes',
      value: 'Notes',
      type: 'MultiLineTextBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 350,
      group: 'Others',
    },
    {
      element: 'facets',
      key: 'manufacturer',
      value: 'Manufacturer',
      type: 'AutoBox',
      validation: {
        allowByPass: true,
        mandatory: true,
      },
      order: 25,
      group: 'Information',
    },
    {
      element: 'facets',
      key: 'model',
      value: 'Model',
      type: 'TextBox',
      validation: {
        allowByPass: true,
        mandatory: true,
      },
      order: 26,
      group: 'Information',
    },
    {
      element: 'facets',
      key: 'maintenance-requirement',
      value: 'Maintenance Requirement',
      type: 'ComboBox',
      validation: {
        mandatory: true,
        allowByPass: false,
      },
      order: 86,
      group: 'Information',
      options: [
        { code: 'Maintain', description: 'Maintain', legacyId: 1 },
        { code: 'Replace', description: 'Replace', legacyId: 2 },
        { code: 'Run to fail', description: 'Run to fail', legacyId: 3 },
      ],
    },
    {
      element: 'facets',
      key: 'rating',
      value: 'Rating (kW)',
      help: 'kW',
      type: 'TextBox',
      validation: {
        allowByPass: true,
        mandatory: true,
        isRegEx: true,
        value : '^[0-9]+$',
        errorMessage: 'Must be a number',
        example: '5',
      },
      order: 1,
      group: 'Others',
    },
  ],
  lifecycle: 10,
  virtual: false,
}
export const tenant = {
  name: 'Edge hill university',
  dns: 'edgehill.co.uk',
  legacy_project_id: 214,
  legacy_hierarchy_id: 47,
  virtual_asset_in_space: true,
  userPoolId: 'eu-west-2_FdbevO5s5',
  userPoolWebClientId: '4mf453i12tr7u7dn3i4un1ecfo',
  assetImagesS3Bucket: 'reams-elias-mwa-dev-tenant1-images',
  identityPoolId: 'eu-west-2:068e05f2-2a40-4755-aaa6-0add576f2f9f',
}
