export default class EditAssetForm {
  completeAsset = () => {
    cy.get('[data-test-selector="ant_select_box"]')
      .eq(0)
      .click()
    cy.get('ul')
      .find('li')
      .contains('B')
      .click()
    cy.get('[data-test-selector="ant_select_box"]')
      .eq(1)
      .click()
    cy.get('ul')
      .find('li')
      .contains('Maintain')
      .click()
    cy.get('[data-test-selector="ant_year_picker"]')
      .clear()
      .type('2019')
    cy.get('[data-test-selector="barcode_input"]')
      .clear()
      .type('123456789')
    cy.get('[data-test-selector="ant_select_box"]')
      .eq(2)
      .click()
    cy.get('ul')
      .find('li')
      .contains('Low Level (<3m)')
      .click()
    cy.get('[data-test-selector="ant_select_box"]')
      .eq(3)
      .click()
    cy.get('ul')
      .find('li')
      .contains('Operating')
      .click()
    cy.get('[data-test-selector="ant_select_box"]')
      .eq(4)
      .click()
    cy.get('ul')
      .find('li')
      .contains('Urgent')
      .click()
    cy.get('button[data-test-selector="form-submit"]').click()
  }
}
    